/**
 * Types for Uploads and MediaAsset endpoints
 *
 * See `FRONTEND_ITER2_CONTRACT.md` §4 (MediaAsset) and §4.3-4.4 (upload flow).
 */

import type { ISODate, UUID } from './common';

/**
 * Raw MediaAsset entity as returned by the backend.
 *
 * This is the low-level DTO used by upload endpoints. The admin media library
 * maps it to the camel-cased `MediaFile` shape (see `./media.ts`).
 */
export interface MediaAsset {
  id: UUID;
  key: string;
  url: string;
  contentType: string | null;
  size: number | null;
  width: number | null;
  height: number | null;
  /** Duration in seconds (ffprobe, audio/video only). May be null right after confirm. */
  duration: number | null;
  createdAt: ISODate;
  createdById: UUID;
  isDeleted: boolean;
  deletedAt: ISODate | null;
}

/**
 * Size and MIME whitelist for a single upload category.
 */
export interface UploadLimitsCategory {
  maxSizeMb: number;
  allowedContentTypes: string[];
}

/**
 * Response of `GET /uploads/limits` (public, cacheable per session).
 */
export interface UploadLimits {
  image: UploadLimitsCategory;
  audio: UploadLimitsCategory;
  /** Presigned-upload token TTL in seconds. */
  presignTtlSec: number;
}

/**
 * Upload category accepted by `POST /uploads/presign`.
 */
export type UploadAssetType = 'cover' | 'audio';

/**
 * Request body for `POST /uploads/presign`.
 *
 * Backend generates the storage key — do not send one.
 */
export interface PresignUploadRequest {
  type: UploadAssetType;
  contentType: string;
  size: number;
}

/**
 * Response of `POST /uploads/presign`.
 */
export interface PresignUploadResponse {
  /** Short-lived token scoped to the upload URL (sent as `X-Upload-Token` to `/uploads/direct`). */
  token: string;
  /** Absolute URL to POST the binary body to. */
  uploadUrl: string;
  /** Final storage key generated by the backend. */
  key: string;
}

/**
 * Response of `POST /uploads/confirm?key=...` — resolves the storage key
 * into its public URL after a successful presigned upload.
 */
export interface UploadsConfirmResponse {
  url: string;
}

/**
 * Request body for `POST /media/confirm`.
 *
 * `url` is required by the backend validator (must be a well-formed URL).
 * Obtain it from `POST /uploads/confirm?key=...`.
 */
export interface ConfirmUploadRequest {
  key: string;
  url: string;
  contentType: string;
  size: number;
}
