import type { FC } from 'react';
import { useState } from 'react';
import { Input } from 'antd';
import { Modal } from '@/components/common/Modal';
import styles from './ImportModal.module.scss';

interface ImportModalProps {
  isOpen: boolean;
  onCancel: () => void;
  onImport: (jsonData: string) => Promise<void>;
  isLoading: boolean;
}

export const ImportModal: FC<ImportModalProps> = ({ isOpen, onCancel, onImport, isLoading }) => {
  const [jsonText, setJsonText] = useState('');
  const [error, setError] = useState<string | null>(null);

  const handleConfirm = async () => {
    setError(null);
    if (!jsonText.trim()) {
      setError('Please paste JSON data first.');
      return;
    }

    try {
      // Validate JSON format
      JSON.parse(jsonText);
    } catch (e) {
      setError('Invalid JSON format. Please check the structure.');
      return;
    }
    try {
      await onImport(jsonText);
      setJsonText('');
      onCancel();
    } catch (err) {
      const message = err instanceof Error ? err.message : 'Import failed.';
      setError(message);
    }
  };

  return (
    <Modal
      isOpen={isOpen}
      title="Import Book Data (5 Languages)"
      confirmText={isLoading ? 'Importing...' : 'Import'}
      confirmVariant="primary"
      isConfirmDisabled={isLoading || !jsonText.trim()}
      isLoading={isLoading}
      onCancel={onCancel}
      onConfirm={handleConfirm}
      size="lg"
    >
      <div className={styles.container}>
        <p className={styles.description}>
          Paste the JSON generated by ChatGPT containing book details and translations for 5
          languages.
        </p>
        <Input.TextArea
          rows={12}
          value={jsonText}
          onChange={(e) => setJsonText(e.target.value)}
          placeholder={`{\n  "originalTitle": "The Picture of Dorian Gray",\n  "firstPublishedYear": 1890,\n  "originalLanguage": "English",\n  "translations": {\n    "en": { ... },\n    "ru": { ... }\n  }\n}`}
          disabled={isLoading}
          className={styles.textarea}
        />
        {error && <div className={styles.error}>{error}</div>}
      </div>
    </Modal>
  );
};
